services:
  postgres:
    image: postgres:16
    container_name: movie-db
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - movie_postgres_data:/var/lib/postgresql/data
volumes:
    movie_postgres_data: