spring:
  application:
    name: seat-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: seat-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        enable.auto.commit: false
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true

    listener:
      ack-mode: MANUAL_IMMEDIATE

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/