services:
  postgres:
    image: postgres:16
    container_name: cinema_db
    restart: always
    environment:
      POSTGRES_DB: cinema-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: