spring:
  application:
    name: cinema-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

    consumer:
      group-id: cinema-service-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.cinema.movie_services.event"
    listener:
      ack_mode: MANUAL_IMMEDIATE

app:
  kafka:
    topic:
      cinema-events: cinema-events

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/