spring:
  application:
    name: notification-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}